mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from Content.views import (
    home_view,
    doc_view,
)

from Account.views import (
    register_view,
    login_view,
    account_view,
    logout_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # Content
    path('', home_view, name="home"),
    path('documentation/', doc_view, name="doc"),

    # Account
    path('register/', register_view, name="register"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('logout/', logout_view, name="logout"),

    # Password-rest
     path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='password-reset/password_reset.html',
             subject_template_name='password-reset/password_reset_subject.txt',
             email_template_name='password-reset/password_reset_email.html',
             success_url='done'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password-reset/password_reset_confirm.html',
         ),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    # Password-change
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='password-change/password_change_done.html'
         ),
        name='password_change_done'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(
             template_name='password-change/password_change.html'
         ),
        name='password_change'),
]

Account/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class UserAccountManager(BaseUserManager):

    def create_user(self, email, password):

        if not email:
            raise ValueError('Email address is required!')

        email = self.normalize_email(email)
        user = self.model(
            email = email
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):

        if not email:
            raise ValueError('Email address is required!')

        email = self.normalize_email(email)
        user = self.create_user(
            email,
            password=password,
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class UserAccount(AbstractBaseUser):

    email = models.EmailField(unique=True, primary_key=True)
    api_key = models.UUIDField(default=uuid.uuid4, editable=False)
    daily_limit = models.IntegerField(default=1000)

    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now_add=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = UserAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "User"

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return True

Content/models.py
from django.db import models

# Create your models here.

Metadata/models.py
from django.db import models

# Create your models here.

Account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from .models import UserAccount


class RegistrationForm(UserCreationForm):

	email = forms.EmailField(max_length=60, help_text='Required!')

	class Meta:
		model = UserAccount
		fields = ("email","password1","password2")


class LoginForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = UserAccount
		fields = ('email','password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid Login Details")

Account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout

from .forms import RegistrationForm, LoginForm


def register_view(request):
    
    user = request.user
    if user.is_authenticated:
        return redirect('home')

    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            return redirect('home')
        
        else:
            context['registration_form'] = form
            
    else:  # GET request
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request, 'account/register.html', context)
    
    
def login_view(request):
    
    user = request.user
    if user.is_authenticated:
        return redirect('home')
    
    context = {}
    if request.POST:
        form = LoginForm(request.POST)
        
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                return redirect('home')

    else:
        form = LoginForm()

    context['login_form'] = form
    return render(request, 'account/login.html', context)
    
    
def account_view(request):
    
    if not request.user.is_authenticated:
        return redirect('login')

    context = {}  
    context['email'] = request.user.email
    context['api_key'] = request.user.api_key
    context['daily_limit'] = request.user.daily_limit

    return render(request, 'account/account.html', context)
    
    
def logout_view(request):
    
    logout(request)
    return redirect('home')

#1@XxYyZz
#1@AaBbCc

Content/views.py
from django.shortcuts import render

# Create your views here.
def home_view(request):
    return render(request, "home.html")


# TODO Build This Page
def doc_view(request):
    return render(request, "home.html")

Metadata/views.py
from django.shortcuts import render

# Create your views here.

Content/templates/home.html
{% extends 'base1.html' %}



		{% block content %}

</style>

	<section class="pt-100 mb-120 text-center justify-content-center align-items-center  call_to_action_2" style="background-color:"#121212"">
		
			
					<h2 class="mb-40 small " data-aos="zoom-in" data-aos-delay="0">
						Open Source API for Web Metadata Retrival 
					</h2>
					<div data-aos="zoom-in" data-aos-delay="250">
					{% if request.user.is_authenticated %}
						<a href="{% url 'doc' %}" class="btn md action-1 ">
							Read docs
						</a>
						{% else %}
						<a href="{% url 'register' %}" class="btn md action-3 ">
							Get Started
						</a>

						 {% endif %}
				
			</div>
		</section>
		
		{% endblock content %}

templates/base1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" >
		<title>Project</title>
		
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
	


		<link rel="icon" href="{% static 'content/i/favicon.png' %}" type="image/x-icon">
		
		<link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@100;200;300;400;500;600;700;800;900&family=Nunito+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
		
		<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
		
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
		
		<link href="https://unpkg.com/aos@2.3.4/dist/aos.css" rel="stylesheet">
		
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
		
	<link rel="stylesheet" href="{% static 'styles.css' %} ">
		<link href="{% static 'content/css/style.min.css'%} " rel="stylesheet" />
		
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	</head> 
	<body>
	<div class='spinner-wrapper'>
    	<div class="spinner"></div>
	</div>
<!-- Navbar -->
	<nav class="pt-30 pb-30 lh-40 navigation_2" style="background-color:"#121212"">
		<div class="container px-xl-0">
			<div class="row align-items-center justify-content-between">
				<div class="col-xl-2 col-lg-3 text-center text-lg-left">
					<a href="{% url 'home' %}" class="mr-20 link img_link">
					<h4 style="color:black;font-weight:600">WMDR</h4>
					
						
					</a>
				</div>
				<div class="col-xl-10 col-lg-9 d-flex flex-wrap align-items-center justify-content-center justify-content-md-between">
					<div class="mb-10 mb-md-0" data-aos="zoom-in" data-aos-delay="250">
						<div class="d-inline-block px-20 dropdown">
							<a href="{% url 'doc' %}" style="color:black;font-weight:600" class="link dropdown-toggle f-20" id="navigation_2_dropdown_1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" placeholder="">
								Documentation
							</a>
							<div class="dropdown-menu bg-dark" aria-labelledby="navigation_2_dropdown_1">
								{% comment %} <div>
									<a href="#" class="link color-main">
										index 1
									</a>
								</div>
								<div>
									<a href="#" class="link color-action-1">
										index 2
									</a>
								</div>
								<div>
									<a href="#" class="link color-main">
										index 3
									</a>
								</div> {% endcomment %}
							</div>
						</div>
					</div>

					<div class="text-md-right" data-aos="zoom-in" data-aos-delay="500">
						<a href="#" class="link mx-15 f-20" style="color:black;font-weight:600">
							Help
						</a>
						  {% if request.user.is_authenticated %}
						  <a href="{% url 'logout' %}" style="color:black;font-weight:600" class="btn mx-15 sm color-main border-gray f-16 action-2">
							Logout
						</a>
							<a href="{% url 'account' %}" style="color:red;font-weight:600" class="btn mx-15 sm  f-16 ">
							<i class="far fa-user-circle" style="height:50px"></i>

								</a>
						{% else %}
						<a href="{% url 'login' %}" style="color:black;font-weight:600" class="link mx-15 color-main f-20">
							Login
						</a>
						<a href="{% url 'register' %}" style="color:black;font-weight:600" class="btn mx-15 sm color-main border-gray f-16 action-2">
							Get an API key
						</a>
						 {% endif %}
					</div>
				</div>
			</div>
		</div>
	</nav>




	{% block content %}

		{% endblock content %}



    	<!-- Footer-->
			<footer class=" text-center footer_1" style="background-color:"#121212"">
				<div class="container px-xl-0">
					<div class="row justify-content-between align-items-center lh-40 links">
						<div class="col-lg-4 col-sm-6 text-sm-right text-lg-left order-1 order-lg-0" data-aos="zoom-in" data-aos-delay="250">
							<a href="#" class="link mr-15" style="color:black;font-weight:600">
								About our team
							</a>
							
							
						</div>
						<div class="mb-10 mb-lg-0 col-lg-auto order-0">
							<a href="{% url 'home' %}" class="mr-20 link img_link">
								<h4 style="color:black;font-weight:600">WMDR</h4>
							</a>
						</div>
						<div class="col-lg-4 col-sm-6 text-sm-left text-lg-right order-2 order-lg-0" data-aos="zoom-in" data-aos-delay="250">
							
							<a href="https://github.com/WebMetadataRetrieval/15-Web_Metadata_Retrieval" class="mx-15 link" style="color:black;">
								<i class="fab fa-github"></i>
								</i>
							</a>
						</div>
					</div>
					<div class="row justify-content-center">
						<div class="col-xl-4 col-lg-5 col-md-6 col-sm-8" data-aos="zoom-in" data-aos-delay="0">
							<div class="color-heading text-adaptive">
								SE-GROUP 15
								<br>
							</div>
						</div>
					</div>
				</div>
			</footer>
	
	
<script>
    let spinnerWrapper = document.querySelector('.spinner-wrapper');

    window.addEventListener('load', function () {
        // spinnerWrapper.style.display = 'none';
        spinnerWrapper.parentElement.removeChild(spinnerWrapper);
    });
</script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
		
		<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
	
	
		<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
		
		<script src="https://unpkg.com/aos@2.3.4/dist/aos.js"></script>
		
		<script src="{% static 'content/js/jquery.maskedinput.min.js' %}"></script>
		
		<script src="{% static 'content/js/script.js' %} "></script>
	</body>
</html>

templates/password-change/password_change.html
<!-- password Change -->

<!--For Login-->


{% load static %}
 

<head>
    <meta charset="utf-8" >
		<title>Project</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@100;200;300;400;500;600;700;800;900&family=DM+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
		
		<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
		
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
		
		<link href="https://unpkg.com/aos@2.3.4/dist/aos.css" rel="stylesheet">
		
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
			<link rel="stylesheet" href="{% static 'styles.css' %} ">
		<link href="{% static 'account/register/css/style.min.css' %} " rel="stylesheet" />
		
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</head>

<body>

<div class='spinner-wrapper'>
    	<div class="spinner"></div>
	</div>

<section class="form_1 mt-1" style="background-color:"#121212"">
		<div class="container px-xl-0">

<form  class="bg-gray mx-auto mw-430 radius10 pt-30  px-50 mt-1 pb-30" method="post">{% csrf_token %}

 	<h2 class="mb-20 small text-center color-heading" style="color:black">
					Change password
				</h2>

  <input name="old_password" type="password" id="id_old_password" placeholder="Old password" class="input border-dark focus-action-1 color-heading placeholder-heading w-full" required autofocus>

  <input name="new_password1" placeholder="New password" type="password" id="id_new_password1" class="input border-dark focus-action-1 color-heading placeholder-heading w-full mt-10"  required>

   <input name="new_password2"  placeholder="Confirm password" type="password" id="id_new_password2" class="input border-dark focus-action-1 color-heading placeholder-heading w-full mt-10"  required>
<input type="checkbox" class=" mr-5 " onclick="myFunction()">Show Password

  
    {% for field in form %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    {% endfor %}
 
  
  <button class="btn mt-20 action-2 w-full" type="submit" style="margin: 10% auto 15% auto;">Change Password</button>


        	<div class="mt-15 f-18 medium color-dark text-center">
	
						<a href="{% url 'home' %}" class="mx-15 link color-main">
						<i class="fas fa-arrow-circle-left"></i>
								</i>
                				<span>
Go back to Home
					</span>
					
							
					</a>
         
				</div>
        
        
</form>

</div>
	</section>

<script>
    let spinnerWrapper = document.querySelector('.spinner-wrapper');

    window.addEventListener('load', function () {
        // spinnerWrapper.style.display = 'none';
        spinnerWrapper.parentElement.removeChild(spinnerWrapper);
    });
</script>


 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
		
	<script>
function myFunction() {
     const fields = [id_old_password, id_new_password1,id_new_password2]

    fields.forEach( x => {
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    });
   
}
</script>	
	
	
</body>

templates/password-change/password_change_done.html
{% extends 'base1.html' %}
{% block content %}
		<section class="pt-100 pb-100 mb-150 text-center call_to_action_2" style="background-color:"#121212"">
			<div class="container px-xl-0">
			
			<p class="m-auto" style="font-weight:600">Your password has been successfully updated.</p>



					
				</div>
			</div>
     
		</section>
{% endblock content %}

templates/password-reset/password_reset.html
<!-- Reset Password-->





{% load static %}
 

<head>
    <meta charset="utf-8" >
		<title>Project</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@100;200;300;400;500;600;700;800;900&family=DM+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
		
		<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
		
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
		
		<link href="https://unpkg.com/aos@2.3.4/dist/aos.css" rel="stylesheet">
		
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
		<link rel="stylesheet" href="{% static 'styles.css' %} ">
		<link href="{% static 'account/register/css/style.min.css' %} " rel="stylesheet" />
		
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</head>

<body>

<div class='spinner-wrapper'>
    	<div class="spinner"></div>
	</div>
<section class="pt-120  form_1" style="background-color:"#121212"">
		<div class="container px-xl-0">

<form  class="bg-gray mx-auto mw-430 radius10 pt-40 px-50 pb-30" method="post">{% csrf_token %}

 	<h2 class="mb-20 small text-center color-heading" style="color:black">
					Reset Password
				</h2>

     
  <input type="email" name="email" required id="id_email" placeholder="Enter your email address" class="input border-dark focus-action-1 color-heading placeholder-heading w-full" required autofocus>


   {% for field in password_reset_form %}
  
          {% for error in field.errors %}
              <p style="color: red;">{{error}}</p>
          {% endfor %}
  
      {% endfor %}
  
      {% if password_reset_form.non_field_errors %}
  
           <div style="color:red;">
              <p>{{password_reset_form.non_field_errors}}</p>
          </div>
  
      {% endif %}
  
  <button class="btn mt-25 action-2 w-full" type="submit" style="margin: 10% auto 15% auto;">Submit</button>
        	<div class="mt-25 f-18 medium color-dark text-center">
	
						<a href="{% url 'home' %}" class="mx-15 link color-main">
						<i class="fas fa-arrow-circle-left"></i>
								</i>
                				<span>
Go back to Home
					</span>
					
							
					</a>
         
				</div>
        
        
</form>

</div>

	</section>


		
<script>
    let spinnerWrapper = document.querySelector('.spinner-wrapper');

    window.addEventListener('load', function () {
        // spinnerWrapper.style.display = 'none';
        spinnerWrapper.parentElement.removeChild(spinnerWrapper);
    });
</script>

 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
		
	
	
	
</body>

templates/password-reset/password_reset_complete.html
{% extends 'base1.html' %}
{% block content %}
		<section class="pt-100 pb-100 mb-100  text-center call_to_action_2" style="background-color:"#121212"">
			<div class="container px-xl-0">
				
			<p class="m-auto" style="font-weight:600">Your Account has been successfully Recovered.</p>


	<a href="{% url 'login' %}" class="mx-15 link color-main">
							<i class="fas fa-arrow-circle-left"></i>
								</i>
                				<span>
						 Back to login
					</span>							
					</a>
					
				</div>
			</div>
     
		</section>
{% endblock content %}

templates/password-reset/password_reset_confirm.html
<!--Reset password -->





{% load static %}
 

<head>
    <meta charset="utf-8" >
		<title>Project</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@100;200;300;400;500;600;700;800;900&family=DM+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
		
		<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
		
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
		
		<link href="https://unpkg.com/aos@2.3.4/dist/aos.css" rel="stylesheet">
		
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
		
        <link rel="stylesheet" href="{% static 'styles.css' %} ">
		


		<link href="{% static 'account/register/css/style.min.css' %} " rel="stylesheet" />
		
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</head>

<body>

<div class='spinner-wrapper'>
    	<div class="spinner"></div>
	</div>

<section class=" mt-5 form_1" style="background-color:"#121212"">
		<div class="container px-xl-0">
  

<form  class="mx-auto bg-gray mw-430 radius10 pt-40 px-50 pb-30"   method="post">{% csrf_token %}

 	<h2 class="mb-20 small text-center color-heading" style="color:black">
					Reset Password
				</h2>

{% if messages %}
    {% for message in messages %}
      <p class="er_message"><strong>{{message}}</strong></p>
    {% endfor %}
  {% endif %}


  <input type="password" id="id_new_password1" name="new_password1"  placeholder="New password" class="input border-dark focus-action-1 color-heading placeholder-heading w-full" required>

  <input type="password" id="id_new_password2" name="new_password2" placeholder="New confirm password"  class="input border-dark focus-action-1 color-heading placeholder-heading w-full mt-10"   required>
  <input type="checkbox" class=" mr-5" onclick="myFunction()">Show Password

 {% for field in form %}

        {% for error in field.errors %}
            <p style="color: red;">{{error}}</p>
        {% endfor %}

    {% endfor %}

    {% if form.non_field_errors %}

         <div style="color:red;">
            <p>{{form.non_field_errors}}</p>
        </div>

    {% endif %}
  
  <button class="btn mt-25 action-2 w-full" type="submit" style="margin: 10% auto 15% auto;">Reset</button>


        	<div class="mt-10 f-18 medium color-dark text-center">
	
						<a href="{% url 'home' %}" class="mx-15 link color-main">
						<i class="fas fa-arrow-circle-left"></i>
								</i>
                				<span>
Go back to Home
					</span>
					
							
					</a>
         
				</div>
        
        
</form>

</div>

	</section>


    	
<script>
    let spinnerWrapper = document.querySelector('.spinner-wrapper');

    window.addEventListener('load', function () {
        // spinnerWrapper.style.display = 'none';
        spinnerWrapper.parentElement.removeChild(spinnerWrapper);
    });
</script>

 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
		<script>
function myFunction() {
     const fields = [ id_new_password1,id_new_password2]

    fields.forEach( x => {
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    });
   
}
</script>		
	
	
	
</body>

templates/password-reset/password_reset_done.html
<!--Password Reset succesfully send email-->



{% extends 'base1.html' %}

{% block content %}
		<section class="pt-100 pb-100 mb-100 text-center call_to_action_2" style="background-color:"#121212"">
			<div class="container px-xl-0">
				
			<p class="m-auto"style="font-weight:600">We have sent you reset password link on your email. Please Check Your Email.</p>
   
						<a href="{% url 'home' %}" class="mx-15 link color-main">
						<i class="fas fa-arrow-circle-left"></i>
								</i>
                				<span>
Go back to Home
					</span>
					
							
					</a>
					</div>
				
			
     
		</section>

{% endblock content %}

		

templates/password-reset/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}Hey, You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}